// Code generated by hertz generator.

package post_category

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _post_categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appendpostcategoryMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTAdmin())
	//return handleFuncs
	return nil
}

func _deletepostcategoryMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTAdmin())
	//return handleFuncs
	return nil
}

func _getspostcategoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepostcategoryMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTAdmin())
	//return handleFuncs
	return nil
}
