// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"resume-resolving/internal/app/web/router/department"
	"resume-resolving/internal/app/web/router/post"
	"resume-resolving/internal/app/web/router/post_category"
	"resume-resolving/internal/app/web/router/resume"
	user "resume-resolving/internal/app/web/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)
	resume.Register(r)
	post.Register(r)
	department.Register(r)
	post_category.Register(r)
}
