// Code generated by Kitex v0.5.2. DO NOT EDIT.

package resumerpcservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	resume "resume-resolving/api/idl/service/resume/kitex_gen/resume"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UploadStructResume(ctx context.Context, request *resume.UploadStructResumeRPCRequest, callOptions ...callopt.Option) (r *resume.UploadStructResumeRPCResponse, err error)
	GetResumeById(ctx context.Context, request *resume.GetResumeByIdRPCRequest, callOptions ...callopt.Option) (r *resume.GetResumeByIdRPCResponse, err error)
	GetResumeByPost(ctx context.Context, request *resume.GetResumeByPostRPCRequest, callOptions ...callopt.Option) (r *resume.GetResumeByPostRPCResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kResumeRPCServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kResumeRPCServiceClient struct {
	*kClient
}

func (p *kResumeRPCServiceClient) UploadStructResume(ctx context.Context, request *resume.UploadStructResumeRPCRequest, callOptions ...callopt.Option) (r *resume.UploadStructResumeRPCResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadStructResume(ctx, request)
}

func (p *kResumeRPCServiceClient) GetResumeById(ctx context.Context, request *resume.GetResumeByIdRPCRequest, callOptions ...callopt.Option) (r *resume.GetResumeByIdRPCResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetResumeById(ctx, request)
}

func (p *kResumeRPCServiceClient) GetResumeByPost(ctx context.Context, request *resume.GetResumeByPostRPCRequest, callOptions ...callopt.Option) (r *resume.GetResumeByPostRPCResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetResumeByPost(ctx, request)
}
