// Code generated by Kitex v0.5.2. DO NOT EDIT.
package resumerpcservice

import (
	server "github.com/cloudwego/kitex/server"
	resume "resume-resolving/api/idl/service/resume/kitex_gen/resume"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler resume.ResumeRPCService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
