// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userchangepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbynameMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTUser())
	//return handleFuncs
	return nil
}

func _gethrbynameMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTHrAdmin())
	//return handleFuncs
	return nil
}

func _gethrbydepartmentMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTAdmin())
	//return handleFuncs
	return nil
}

func _hrdeleteMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTAdmin())
	//return handleFuncs
	return nil
}

func _hrregisterMw() []app.HandlerFunc {
	//var handleFuncs []app.HandlerFunc
	//handleFuncs = append(
	//	handleFuncs,
	//	web.GlobalEngine.Options.Jwt.AuthMiddleware.MiddlewareFunc(),
	//	middleware.JWTAdmin())
	//return handleFuncs
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}
