// Code generated by hertz generator.

package department

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _departmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appenddepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsdepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _appendcityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getscityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getscitybydepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}
